on:
  workflow_dispatch:

name: relase
jobs:
  build_windows:
    name: Build Windows ${{matrix.platform}} ${{matrix.type}} ${{matrix.openmp}}
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform: [ x64, arm64, x86 ]
        type: [ dynamic, static ]
        openmp: [ openMP, noOpenMP ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout ImageMagick-Windows
      uses: actions/checkout@v4
      with:
        repository: ImageMagick/ImageMagick-Windows
        path: ./ImageMagick-Windows
        ref: refs/heads/new-config

    - name: Clone dependencies
      shell: cmd
      run: CloneDependencies.cmd

    - name: Build configure
      shell: cmd
      working-directory: ImageMagick-Windows\Configure
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild Configure.sln /m /t:Rebuild /p:Configuration=Release,Platform=x64
        copy Artifacts\Release\x64\bin\Configure.Release.x64.exe Configure.Release.x64.exe

    - name: Run configure
      shell: cmd
      working-directory: ImageMagick-Windows\Configure
      run: |
        Configure.Release.x64.exe /noWizard /VS2022 /${{ matrix.platform }} /${{ matrix.type }} /${{ matrix.openmp }}

    - name: Build dependencies
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd ImageMagick-Windows
        msbuild IM7.${{ matrix.type }}.${{matrix.platform}}.sln /m /t:Rebuild /p:Configuration=Release,Platform=${{matrix.platform}}

    - name: Prepare artifacts
      shell: cmd
      run: |
        mkdir Artifacts
        robocopy "ImageMagick-Windows\Artifacts" "Artifacts" *.dll *.lib *.h *.txt /S /COPYALL /NP
        if %ERRORLEVEL% NEQ 1 (
          echo Error: robocopy failed with exit code %ERRORLEVEL%
          exit /b 1
        )
        exit /b 0

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.type }}-${{ matrix.openmp }}
        path: Artifacts
